# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b70fd599dee264f509689bb5f79387b08110c58b2ca1d5bd6134a582e1fd3424f64d33618d4cb71cda2cc76df5b3542e2bb5934cec7bb26a7ea259e3656be38c

test:
  secret_key_base: ab4571675b6ebb9ba7c8e6efcec24e1cd7b4cef85caba80308b69a1d2373a16cf7ac0f300dca4eb4e6fded045618783234de000de218b8852c3a9ad7978fb9eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
